version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: node src/workers/emailWorker.js
