version: "3.8"

services:
  mainserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"

  globalworker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: node src/workers/globalWorker.js
